name: publish docs

on:
  workflow_dispatch:
  push:
    tags:
    - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  docs:
    permissions:
      contents: write
    uses: ./.github/workflows/docs.yml

  publish:
    name: Publish documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
    - docs

    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: documentation
        path: site

    - uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453  # v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
